#!/usr/bin/env python3
# Portrait-derived ASCII source used by the profile SVG.
ASCII = r"""                        ..        ..................
                   .r3hMGSMh5Xr;.   ................
               ,X3H#&@&&&BB&&B99Shr. ...............
             .29B&&B#9BBB9##9BS#S9&Gi   ............
            sSBB9BBB999##9#9B9#9#S9&92:  ...........
           .SBB99999#99BB99#B99B9B9B&&#s  ..........
           sB999#GHMMMHGGH32A253hG9&&&&Bi  .........
          ,GB9G5Xri;;:;;;::::;;is2G9B9B&A  .........
           H9S5ri;:::::::::,::;;iis5HS##:   ... ....
           29HArirrri;;;;::::;;iirrX3HSM        ....
           ;S5A222AXi:::::::;irss22sshG5..      ....
          :rS33hhhMHH3Xi;;s2hHMhhhh5X3GXsr.    .....
         .2shh2233hH52AX;;sX22hH3h2AA55;;s.    .....
         .Xs53sX2AA2rrrXi;rrrsXAXAsssA5rii.     ....
          i25hXri;;;;;sXrisri;;;;;irs25rr:     .....
           iXM5sr;:::;ssi;rsi:::;;rsXM2i:       ....
            ,5GAsr;;:iX2siXAr;::irXAhHi.     .......
             .MG5Xriis5HHhMH5XsrrA5H#h     .........
              ;9#M53G#99#SS#99#Shh#BB5    ..........
               3BB99#GM32AA253h#99BB#r    . ........
               .H&B9S35hHHHGM23#9BBBh.    ..........
                ,S&B#SSHM3MGSS#9999H2     ..........
                .2G999GMGGSGSS99BSM5A.     .........
                .AA53HHGSS##99SM35555i.    .........
           .,;XMSh2XrrX255535AXrA2A22MHXi..     ....
     ..:rAMS9B&BBB#SH32AXssrrrrs23MHG9BBB#GMA;:.
;s2hG#9BBBBBBBBBBBBBBBBB9#SS###99BBBBBBBBBBBBB9SH32s
B&&&BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB&B
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"""
PROFILE = {
    "name": "turkoise@github",
    "os": "macOS",
    "location": "Bulgaria",
    "role": "Frontend Developer",
    "status": "Open to work",
    "languages": "JavaScript, TypeScript, C#, Swift",
    "frameworks": "React, Next.js, React Native, Vite",
    "frontend": "Tailwind CSS, HTML, CSS",
    "backend": "Node.js, Supabase, REST APIs",
    "tools": "Git, GitHub, Figma, VS Code",
}
print("Detailed portrait ASCII profile source loaded.")
